import { createHash } from "node:crypto";
import path from "node:path";
import { lstat, readFile, realpath } from "node:fs/promises";
import { HtmlValidate } from "html-validate";
import { ESLint } from "eslint";
import stylelint from "stylelint";
import { canonicalJson, type JsonValue } from "../artifact-canonical.js";
import {
  checkPrototypeJourneyPlan,
  compilePrototypeJourney,
  type PrototypeJourneyInput,
} from "../prototype-journey/index.js";
import {
  markedJourneyModePlan,
  type PrototypeJourneyModePlan,
} from "../prototype-modes/journey.js";
import {
  inspectBundle,
  type GateFinding,
  type GateInput,
  type InspectedBundle,
  type QualityReport,
} from "./index.js";

const hash = (value: string) =>
  "sha256:" + createHash("sha256").update(value).digest("hex");
function finding(
  criterion: string,
  state: GateFinding["state"],
  reason: string,
  target: InspectedBundle,
  evidence: readonly string[] = ["plan.json", "manifest.json"],
): GateFinding {
  return {
    criterion,
    state,
    severity: "MAJOR",
    reason,
    evidence,
    conditions: { bundleDigest: target.target.bundleDigest, synthetic: true },
    limitations:
      "Generated synthetic specification only; no human approval or empirical usability is inferred",
  };
}
async function metadata(directory: string, name: string): Promise<unknown> {
  const file = path.join(directory, name);
  const stat = await lstat(file);
  if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 2_000_000)
    return undefined;
  return JSON.parse(await readFile(file, "utf8")) as unknown;
}
async function journeyLocation(
  root: string,
  directory: string,
  plan: PrototypeJourneyInput,
): Promise<boolean> {
  if (path.resolve(root, plan.outputPath) === directory) return true;
  const comparisonDirectory = path.dirname(directory);
  if (
    path.dirname(comparisonDirectory) !== root ||
    path.basename(directory) !== plan.outputPath
  )
    return false;
  try {
    const rawMode = await metadata(comparisonDirectory, "mode-plan.json");
    const rawComparison = await metadata(
      comparisonDirectory,
      "comparison.json",
    );
    if (
      !rawMode ||
      !rawComparison ||
      typeof rawMode !== "object" ||
      typeof rawComparison !== "object"
    )
      return false;
    const mode = rawMode as PrototypeJourneyModePlan;
    const comparison = rawComparison as Record<string, unknown>;
    const slot =
      plan.outputPath === mode.current?.outputPath
        ? "current"
        : plan.outputPath === mode.proposed?.outputPath
          ? "proposed"
          : undefined;
    if (
      !slot ||
      mode.comparisonPath !== path.basename(comparisonDirectory) ||
      comparison.kind !== "mimic-prototype-journey-mode-comparison" ||
      comparison.productionReady !== false ||
      comparison.modePlanDigest !==
        hash(canonicalJson(mode as unknown as JsonValue)) ||
      canonicalJson(comparison.contract) !== canonicalJson(mode.contract) ||
      canonicalJson(comparison.journey) !==
        canonicalJson(mode.current.journey) ||
      canonicalJson(comparison.decisionContext) !==
        canonicalJson(mode.decisionContext) ||
      canonicalJson(comparison.choices) !==
        canonicalJson(
          mode.choices.filter(
            (choice) =>
              mode.currentUses.includes(choice.id) ||
              mode.proposedUses.includes(choice.id),
          ),
        )
    )
      return false;
    const advertised = comparison[slot] as {
      path?: unknown;
      planDigest?: unknown;
    } | null;
    if (
      !advertised ||
      advertised.path !== plan.outputPath ||
      advertised.planDigest !==
        hash(canonicalJson(plan as unknown as JsonValue))
    )
      return false;
    if (slot === "current")
      return (
        canonicalJson(mode.current as unknown as JsonValue) ===
        canonicalJson(plan as unknown as JsonValue)
      );
    if (comparison.fallback !== null || !comparison.proposed) return false;
    const expected = markedJourneyModePlan(
      mode.proposed,
      mode.choices.filter((choice) => mode.proposedUses.includes(choice.id)),
      mode.decisionContext.kind === "historical",
    );
    return (
      canonicalJson(expected as unknown as JsonValue) ===
      canonicalJson(plan as unknown as JsonValue)
    );
  } catch {
    return false;
  }
}
/** Exact generated bytes are compared with a fresh compilation from the saved authored plan. */
export async function runStaticJourneyQualityGates(
  input: GateInput,
  inspected?: InspectedBundle,
): Promise<{ report: QualityReport; bundle: InspectedBundle }> {
  const bundle = inspected ?? (await inspectBundle(input));
  const checked = checkPrototypeJourneyPlan(bundle.plan);
  const plan = checked.plan;
  const manifest = bundle.manifest;
  const root = await realpath(input.trustedRoot);
  const location =
    !!plan && (await journeyLocation(root, bundle.target.directory, plan));
  const declared =
    !!plan &&
    !!manifest &&
    manifest.kind === "mimic-prototype-journey" &&
    manifest.productionReady === false &&
    manifest.fixtures === "synthetic" &&
    manifest.planDigest === hash(canonicalJson(plan as unknown as JsonValue)) &&
    location &&
    Array.isArray(manifest.views) &&
    canonicalJson(
      (manifest.views as unknown[]).map(
        (view) => (view as { id?: unknown }).id,
      ),
    ) === canonicalJson(plan.views.map((view) => view.id)) &&
    canonicalJson(manifest.contract) === canonicalJson(plan.contract) &&
    canonicalJson(manifest.journey) === canonicalJson(plan.journey);
  const findings: GateFinding[] = [
    finding(
      "bundle-manifest",
      declared ? "PASS" : "FAIL",
      declared
        ? "Saved journey plan, version, digest, manifest and output location match"
        : "Malformed, unsupported, or mismatched journey plan: " +
            checked.errors.join("; "),
      bundle,
    ),
  ];
  let exact = false;
  if (!input.store) {
    findings.push(
      finding(
        "source-locks",
        "UNVERIFIED",
        "ArtifactStore unavailable for exact source and emitted byte verification",
        bundle,
      ),
    );
    findings.push(
      finding(
        "artifact-validity",
        "UNVERIFIED",
        "ArtifactStore unavailable",
        bundle,
      ),
    );
  } else if (!declared || !plan) {
    findings.push(
      finding("source-locks", "FAIL", "Journey declaration is invalid", bundle),
    );
    findings.push(
      finding(
        "artifact-validity",
        "UNVERIFIED",
        "Invalid journey declaration prevents source reads",
        bundle,
      ),
    );
  } else {
    try {
      const fresh = await compilePrototypeJourney(input.store, plan);
      const names = Object.keys(fresh.files);
      exact =
        names.length === Object.keys(bundle.target.files).length &&
        names.every(
          (name) => bundle.target.files[name] === hash(fresh.files[name]!),
        );
      findings.push(
        finding(
          "source-locks",
          exact ? "PASS" : "FAIL",
          exact
            ? "All five emitted files match a fresh compilation of the saved plan and exact approved sources"
            : "Emitted bundle differs from the saved plan and exact sources",
          bundle,
          names,
        ),
      );
      findings.push(
        finding(
          "artifact-validity",
          "PASS",
          "Product UI Contract, Product journey, each own-domain scenario, selected assets and tokens were read under exact approved locks",
          bundle,
          [
            plan.contract.artifactId,
            plan.journey.artifactId,
            ...plan.views.map((view) => view.render.scenario.artifactId),
          ],
        ),
      );
    } catch (error) {
      const message = String(error);
      const unavailable =
        /UNAVAILABLE|UNVERIFIED|EIO|ENETDOWN|ETIMEDOUT|ECONNRESET/.test(
          message,
        );
      findings.push(
        finding(
          "source-locks",
          unavailable ? "UNVERIFIED" : "FAIL",
          message,
          bundle,
        ),
      );
      findings.push(
        finding(
          "artifact-validity",
          unavailable ? "UNVERIFIED" : "FAIL",
          message,
          bundle,
        ),
      );
    }
  }
  const controls = plan?.controls.length ?? 0;
  findings.push(
    finding(
      "finite-actions",
      declared && exact && controls > 0 ? "PASS" : "FAIL",
      declared && exact && controls > 0
        ? controls +
            " authored controls are bound to a finite validated action set"
        : "Finite action declarations or exact emitted binding are missing",
      bundle,
      ["plan.json", "prototype.js"],
    ),
  );
  try {
    const result = await new HtmlValidate({
      extends: ["html-validate:recommended"],
      rules: {
        "doctype-style": ["error", { style: "lowercase" }],
        "void-style": ["error", { style: "selfclose" }],
      },
    }).validateString(bundle.html, "index.html");
    findings.push(
      finding(
        "html-lint",
        result.valid ? "PASS" : "FAIL",
        result.valid
          ? "html-validate passed"
          : result.results
              .flatMap((item) =>
                item.messages.map(
                  (message) => message.ruleId + ": " + message.message,
                ),
              )
              .join("; "),
        bundle,
        ["index.html"],
      ),
    );
  } catch (error) {
    findings.push(
      finding("html-lint", "UNVERIFIED", String(error), bundle, ["index.html"]),
    );
  }
  try {
    const eslint = new ESLint({
      overrideConfigFile: true,
      overrideConfig: [
        {
          languageOptions: {
            globals: {
              document: "readonly",
              window: "readonly",
              location: "readonly",
              history: "readonly",
              queueMicrotask: "readonly",
              Map: "readonly",
              Set: "readonly",
              URL: "readonly",
            },
          },
          rules: { "no-undef": "error", "no-unused-vars": "error" },
        },
      ],
    });
    const [result] = await eslint.lintText(bundle.js, {
      filePath: "prototype.js",
    });
    findings.push(
      finding(
        "javascript-lint",
        result && result.errorCount === 0 ? "PASS" : "FAIL",
        result?.messages
          .map((message) => message.ruleId + ": " + message.message)
          .join("; ") || "ESLint passed",
        bundle,
        ["prototype.js"],
      ),
    );
  } catch (error) {
    findings.push(
      finding("javascript-lint", "UNVERIFIED", String(error), bundle, [
        "prototype.js",
      ]),
    );
  }
  try {
    const result = await stylelint.lint({
      code: bundle.css,
      codeFilename: "prototype.css",
      config: {
        rules: {
          "block-no-empty": true,
          "color-no-invalid-hex": true,
          "declaration-block-no-duplicate-properties": true,
        },
      },
    });
    findings.push(
      finding(
        "css-lint",
        result.errored ? "FAIL" : "PASS",
        result.errored
          ? result.results
              .flatMap((item) => item.warnings.map((warning) => warning.text))
              .join("; ")
          : "Stylelint passed",
        bundle,
        ["prototype.css"],
      ),
    );
  } catch (error) {
    findings.push(
      finding("css-lint", "UNVERIFIED", String(error), bundle, [
        "prototype.css",
      ]),
    );
  }
  const sameContract =
    plan &&
    input.uiContract &&
    canonicalJson(plan.contract) === canonicalJson(input.uiContract);
  findings.push(
    finding(
      "ui-contract-consistency",
      !input.uiContract
        ? "UNVERIFIED"
        : sameContract && exact
          ? "CONCERN"
          : "FAIL",
      !input.uiContract
        ? "No exact Product UI Contract supplied"
        : sameContract && exact
          ? "Exact approved Contract is linked; semantic fidelity still needs review"
          : "Supplied UI Contract is different or source compilation is not verified",
      bundle,
      ["plan.json"],
    ),
  );
  return {
    bundle,
    report: {
      target: bundle.target,
      findings,
      inspectedAt: new Date().toISOString(),
      action: "inspect-only",
    },
  };
}
